### ISSUE TITLE
Update "community/*"

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/wiki#8]
https://k1sslinux.org/wiki/community/repositories is kinda outdated now, should the page just be deleted and [awesome-kiss](https://github.com/kiss-community/awesome-kiss) be linked in [Universe](https://k1sslinux.org/install#3.4) instead ?

**Comment by git-bruh** [comment]
Actually all the pages under community/ are outdated, not sure what's the best approach here.

**Comment by dilyn-corner** [comment]
The best approach is to nuke the page from orbit... 202a66061ba0f669f52e9647903dd0e0d06a4b3b https://github.com/kiss-community/website/commit/0e754c2a6acf5416485c6de9bfda8b8ce32aba32
